#image: docker:latest
image: maven:3-jdk-8

variables:
  DOCKER_DRIVER: overlay
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'
cache:
  paths:
    - .m2/repository

stages:
  - gh-install
  - ors-build
  - ors-api-test

maven-gh-install:
  stage: gh-install
  only: 
    - development
  script: 
    - mvn -f ./graphhopper/pom.xml install -B

maven-ors-build:
  stage: ors-build
  only: 
    - development
  script: 
    - mvn -f ./openrouteservice/pom.xml package -B

maven-ors-api-test:
  stage: ors-api-test
  only: 
    - development
  before_script:
    - nohup mvn -f ./openrouteservice/pom.xml -X tomcat7:run &
  script:
    - mvn -f ./openrouteservice-api-tests/pom.xml test
